apiVersion: v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    project: expense
    environment: dev
spec:
  replicas: 2
  selectors: 
    matchLabels:
      name: nodejs
      project: expense
  template:
    metadata:
      labels:
        name: nodejs
        project: expense
    spec:
      containers:
      - name: nodejs
        image: nodejs:v1.2
