apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: expense
    environment: dev
spec:
  replicas: 2
  selectors: 
    matchLabels:
      name: mysql
      project: expense
  template:
    metadata:
      labels:
        name: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: mysql:v1.2